id: 3595f9c5bfc445f79d33952635a06ef4
initial_creation_type: ocr
source_metadata:
  volumes:
    04d48947a6c84d9d9f3ba01fc22774ea:
      base_file: v056.txt
      image_group_id: I1PD95902
      title: ''
      total_pages: 1605
      volume_number: 57
